#!/bin/bash

echo REACT_APP_LOADBALANCER_HTTP_URI="$REACT_APP_LOADBALANCER_HTTP_URI" >> .env
echo REACT_APP_LOADBALANCER_WS_URI="$REACT_APP_LOADBALANCER_WS_URI" >> .env
echo REACT_APP_ENVIRONMENT="$REACT_APP_ENVIRONMENT" >> .env
echo SKIP_PREFLIGHT_CHECK="true" >> .env
